version: 2

models:
  - name: int_kpis2
    description: "Intermediate model that engineers strategic KPIs for Client risk and exposure analysis"
    columns:
      - name: loan_id
        description: "Unique identifier for each loan"
        tests:
          - not_null
          - unique

      - name: client_debt_to_income_proxy
        description: "{{ doc('client_debt_to_income_proxy') }}"
        tests:
          - not_null

      - name: months_active
        description: "{{ doc('months_acitvie') }}"
        tests:
          - not_null

      - name: dti_band
        description: "{{ doc('dti_band')}}"
        tests:
          - not_null
          - accepted_values:
              values:
                - "High Burden"
                - "Medium Burden"
                - "Low Burden"