models:
  - name: dim_client
    description: "Dimension table contain client-level attributes"
    columns:
      - name: client_id
        description: "Unique Identifier for each client"
        tests:
          - not_null
          - unique

  - name: dim_time
    description: "Time dimension table for calendar-based joins and analysis"
    columns:
      - name: date
        description: "Primary key for time dimension"
        tests:
          - not_null
          - unique
