name: 'dbt_bq_credit_risk'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["models/marts/fact"]
  # ✅ This is correct for your client_segmentation_docs.md file

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bq_credit_risk:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
