version: 2

models:
  - name: fct_client_risk
    description: "Mart model that segments clients by risk and value using engineered KPIs"
    columns:
      - name: loan_id
        description: "Unique identifier for each loan"
        tests:
          - not_null
          - unique

      - name: client_risk_segment
        description: "{{ doc('client_risk_segment') }}"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - "High Risk - New"
                  - "High Risk - Long Term"
                  - "Medium Risk"
                  - "Low Risk"

      - name: high_value_flag
        description: "{{ doc('high_value_flag') }}"
        tests:
          - not_null

      - name: monthly_capital_exposure_kpi
        description: "{{ doc('monthly_capital_exposure') }}"
        tests:
          - not_null

      - name: client_debt_to_income_proxy
        description: "{{ doc('client_debt_to_income_proxy') }}"
        tests:
          - not_null

      - name: months_active
        description: "{{ doc('months_active') }}"
        tests:
          - not_null

      - name: dti_band
        description: "{{ doc('dti_band') }}"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - "High Burden"
                  - "Medium Burden"
                  - "Low Burden"
